const tracks = [
{id:'crown-street-afterimage',title:'Crown Street Afterimage',artist:'Fuse House Band',album:'Night Market Sessions',bpm:92,mood:'Deep pocket drums, muted Rhodes, glassy guitar',duration:'0:22',src:'assets/audio/crown-street-afterimage.mp3',cover:'assets/covers/crown-street-afterimage.svg'},
{id:'surry-line',title:'Surry Line',artist:'Fuse House Band',album:'Night Market Sessions',bpm:124,mood:'Percussive synth bass, hand claps, bright piano stabs',duration:'0:22',src:'assets/audio/surry-line.mp3',cover:'assets/covers/surry-line.svg'},
{id:'harbour-plainclothes',title:'Harbour Plainclothes',artist:'Mara Vale',album:'Blue Hour Mechanics',bpm:106,mood:'Warm bass, brushed kit, restrained sax phrases',duration:'0:22',src:'assets/audio/harbour-plainclothes.mp3',cover:'assets/covers/harbour-plainclothes.svg'},
{id:'redfern-current',title:'Redfern Current',artist:'Mara Vale',album:'Blue Hour Mechanics',bpm:118,mood:'Tight broken beat with kalimba and analogue pads',duration:'0:22',src:'assets/audio/redfern-current.mp3',cover:'assets/covers/redfern-current.svg'},
{id:'nocturne-for-499',title:'Nocturne for 499',artist:'The Switch Room',album:'Fuse Originals',bpm:78,mood:'Slow instrumental pulse with bowed keys and sub movement',duration:'0:22',src:'assets/audio/nocturne-for-499.mp3',cover:'assets/covers/nocturne-for-499.svg'},
{id:'sixteen-lanes',title:'Sixteen Lanes',artist:'The Switch Room',album:'Fuse Originals',bpm:132,mood:'Motorik drums, arpeggiated bass, dry snare, no filler',duration:'0:22',src:'assets/audio/sixteen-lanes.mp3',cover:'assets/covers/sixteen-lanes.svg'},
{id:'paper-ticket-sunrise',title:'Paper Ticket Sunrise',artist:'Lio & The Machines',album:'Transit Choir',bpm:98,mood:'Acoustic percussion, marimba hook, soft modular lead',duration:'0:22',src:'assets/audio/paper-ticket-sunrise.mp3',cover:'assets/covers/paper-ticket-sunrise.svg'},
{id:'platform-echo',title:'Platform Echo',artist:'Lio & The Machines',album:'Transit Choir',bpm:112,mood:'Dub chords, roomy toms, tape-flutter lead',duration:'0:22',src:'assets/audio/platform-echo.mp3',cover:'assets/covers/platform-echo.svg'},
{id:'king-tide-edit',title:'King Tide Edit',artist:'Northbound Fiction',album:'Coastal Pressure',bpm:128,mood:'Clean club instrumental with surf guitar fragments',duration:'0:22',src:'assets/audio/king-tide-edit.mp3',cover:'assets/covers/king-tide-edit.svg'},
{id:'after-hours-ledger',title:'After Hours Ledger',artist:'Northbound Fiction',album:'Coastal Pressure',bpm:88,mood:'Late jazz bass, clipped drums, tremolo organ',duration:'0:22',src:'assets/audio/after-hours-ledger.mp3',cover:'assets/covers/after-hours-ledger.svg'},
{id:'signal-at-central',title:'Signal at Central',artist:'Ota Minute',album:'Platform Studies',bpm:116,mood:'Polyrhythmic bells, crisp bass, silver synth melody',duration:'0:22',src:'assets/audio/signal-at-central.mp3',cover:'assets/covers/signal-at-central.svg'},
{id:'last-tram-home',title:'Last Tram Home',artist:'Ota Minute',album:'Platform Studies',bpm:84,mood:'Loping downtempo drums, nylon guitar, dusk pads',duration:'0:22',src:'assets/audio/last-tram-home.mp3',cover:'assets/covers/last-tram-home.svg'}
];
const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
const storeKey = 'fuse-music-v2';
const defaults = {current:0,queue:tracks.map(t=>t.id),liked:[],playlists:{'Night bus': ['crown-street-afterimage','after-hours-ledger','last-tram-home']},shuffle:false,repeat:'off',theme:'dark',volume:.78,recent:[]};
let saved = {};
try { saved = JSON.parse(localStorage.getItem(storeKey) || '{}') || {}; } catch {}
let state = {...defaults,...saved,liked:Array.isArray(saved.liked)?saved.liked:defaults.liked,playlists: saved.playlists && typeof saved.playlists==='object' ? saved.playlists:defaults.playlists};
state.playlists=Object.fromEntries(Object.entries(state.playlists).filter(([name,ids])=>name&&Array.isArray(ids)).map(([name,ids])=>[name,ids.filter((id,index)=>tracks.some(t=>t.id===id)&&ids.indexOf(id)===index)]));
state.queue = (Array.isArray(state.queue)?state.queue:defaults.queue).filter(id=>tracks.some(t=>t.id===id));
if(!state.queue.length) state.queue=[tracks[0].id];
state.current = Math.min(Math.max(0,Number(state.current)||0),state.queue.length-1);
state.volume = Math.min(1,Math.max(0,Number(state.volume)||0));
const audioA=$('#audio'), audioB=new Audio(); audioB.preload='auto';
let active=audioA, standby=audioB, fading=false, fadeFrame=0, searchText='', queuedNext=-1, artistDirectory=[], pendingSetTrack='';
let crossfadeAllowed=true, standbyPrimed=false, lastAudibleVolume=state.volume||.78, noticeTimer=0;
const byId = id => tracks.find(t=>t.id===id);
const current = () => byId(state.queue[state.current]) || tracks[0];
const esc = s => String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const save = () => { try{localStorage.setItem(storeKey,JSON.stringify(state));}catch{} };
const fmt = sec => Number.isFinite(sec)?`${Math.floor(sec/60)}:${String(Math.floor(sec%60)).padStart(2,'0')}`:'0:00';
function announce(message){const el=$('#globalNotice');if(!el)return;clearTimeout(noticeTimer);el.textContent=message;el.classList.add('show');noticeTimer=setTimeout(()=>el.classList.remove('show'),3200)}
window.fuseNotice=announce;
function updateSeekA11y(){const duration=Number.isFinite(active.duration)?active.duration:22,elapsed=Number.isFinite(active.currentTime)?active.currentTime:0,seek=$('#seek');seek.setAttribute('aria-valuenow',seek.value);seek.setAttribute('aria-valuetext',`${fmt(elapsed)} of ${fmt(duration)}`)}
function updateMediaSession(){if(!('mediaSession' in navigator))return;const t=current();try{navigator.mediaSession.metadata=new MediaMetadata({title:t.title,artist:t.artist,album:t.album,artwork:[{src:new URL(t.cover,location.href).href,type:'image/svg+xml'}]});navigator.mediaSession.playbackState=active.paused?'paused':'playing'}catch{}}
function updatePlayer(){const t=current();$('#nowCover').src=t.cover;$('#nowCover').alt=`Artwork for ${t.title}`;$('#nowTitle').textContent=t.title;$('#nowArtist').textContent=`${t.artist} · ${t.album}`;$('#duration').textContent=fmt(active.duration||22);$('#playBtn').textContent=active.paused?'▶':'Ⅱ';$('#playBtn').setAttribute('aria-label',active.paused?'Play':'Pause');$('#shuffleBtn').classList.toggle('liked',state.shuffle);$('#shuffleBtn').setAttribute('aria-pressed',String(state.shuffle));$('#repeatBtn').classList.toggle('liked',state.repeat!=='off');$('#repeatBtn').textContent = state.repeat==='off'?'↻':state.repeat==='one'?'↻₁':'↻';$('#repeatBtn').title=`Repeat ${state.repeat} (R)`;$('#repeatBtn').setAttribute('aria-label',`Repeat ${state.repeat}`);$('#muteBtn').textContent=state.volume===0?'MUTED':'VOL';$('#muteBtn').setAttribute('aria-pressed',String(state.volume===0));$('#muteBtn').setAttribute('aria-label',state.volume===0?'Unmute':'Mute');$$('[data-track-id]').forEach(el=>el.classList.toggle('playing',el.dataset.trackId===t.id));updateSeekA11y();updateMediaSession();}
function prepareStandby(){const nextIndex=nextIndexForPlayback();queuedNext=nextIndex;if(nextIndex>=0 && state.repeat!=='one'){const t=byId(state.queue[nextIndex]);if(t && standby.src!==new URL(t.src,location.href).href){standby.src=t.src;standby.load();}}else{standby.removeAttribute('src');standby.load();}}
function stopFade(){cancelAnimationFrame(fadeFrame);fading=false;standby.pause();standby.volume=0;standby.muted=false;active.volume=state.volume;}
function remember(id){state.recent=[id,...state.recent.filter(x=>x!==id)].slice(0,12);save();}
function loadTrack(play=false){stopFade();active.pause();active.src=current().src;active.load();active.volume=state.volume;$('#elapsed').textContent='0:00';$('#seek').value=0;remember(current().id);updatePlayer();prepareStandby();render();if(play)active.play().catch(()=>{announce('Tap play to start audio on this device.');updatePlayer()});save();}
function playIndex(i){if(i<0||i>=state.queue.length)return;state.current=i;loadTrack(true);}
function playTrack(id){const idx=state.queue.indexOf(id);if(idx<0){state.queue.splice(state.current+1,0,id);state.current++;}else state.current=idx;loadTrack(true);}
function nextIndexForPlayback(){if(state.shuffle&&state.queue.length>1){let i=state.current;while(i===state.current)i=Math.floor(Math.random()*state.queue.length);return i}if(state.current<state.queue.length-1)return state.current+1;if(state.repeat==='all')return 0;return -1}
function next(auto=false){if(auto&&state.repeat==='one'){active.currentTime=0;active.play();return}const i=queuedNext>=0?queuedNext:nextIndexForPlayback();if(i<0){active.pause();updatePlayer();return}state.current=i;loadTrack(true)}
function previous(){if(active.currentTime>3){active.currentTime=0;return}const i=state.current>0?state.current-1:state.queue.length-1;playIndex(i)}
function transition(){if(!crossfadeAllowed||fading||active.paused||state.repeat==='one')return;const i=queuedNext;if(i<0||!standby.src)return;fading=true;const outgoing=active,incoming=standby;incoming.currentTime=0;incoming.volume=0;incoming.play().then(()=>{const started=performance.now(),len=450;function tick(now){const p=Math.min(1,(now-started)/len);outgoing.volume=state.volume*(1-p);incoming.volume=state.volume*p;if(p<1){fadeFrame=requestAnimationFrame(tick)}else{outgoing.pause();outgoing.volume=0;active=incoming;standby=outgoing;fading=false;state.current=i;remember(current().id);updatePlayer();render();prepareStandby();save();}}fadeFrame=requestAnimationFrame(tick)}).catch(()=>{fading=false;crossfadeAllowed=false;if(outgoing.duration-outgoing.currentTime<.8){state.current=i;loadTrack(true)}});}
function addQueue(id){state.queue.push(id);render();prepareStandby();save()}
function toggleLike(id){state.liked=state.liked.includes(id)?state.liked.filter(x=>x!==id):[...state.liked,id];render();save()}
function row(t,i){return `<article class="item" data-track-id="${t.id}"><img src="${t.cover}" alt=""><div><h3>${esc(t.title)}</h3><p>${esc(t.artist)} · ${esc(t.album)} · ${t.bpm} BPM</p></div><div class="item-actions"><button data-action="play" data-id="${t.id}" aria-label="Play ${esc(t.title)}">PLAY</button><button data-action="queue" data-id="${t.id}" aria-label="Queue ${esc(t.title)}">+ QUEUE</button><button data-action="addtoset" data-id="${t.id}" aria-label="Add ${esc(t.title)} to a set">+ SET</button><button class="${state.liked.includes(t.id)?'liked':''}" data-action="like" data-id="${t.id}" aria-label="${state.liked.includes(t.id)?'Unlike':'Like'} ${esc(t.title)}">${state.liked.includes(t.id)?'♥ SAVED':'♡ SAVE'}</button></div></article>`}
function render(){
$('#trackGrid').innerHTML=tracks.map((t,i)=>`<article class="card" data-track-id="${t.id}"><img src="${t.cover}" alt="Artwork for ${esc(t.title)}" loading="lazy"><div class="card-meta"><span>FUSE / ${String(i+1).padStart(2,'0')}</span><span>${t.bpm} BPM</span></div><h3>${esc(t.title)}</h3><p>${esc(t.artist)} · ${esc(t.album)}</p><p class="mood">${esc(t.mood)}</p><div class="row"><button class="primary" data-action="play" data-id="${t.id}" aria-label="Play ${esc(t.title)}">PLAY ↗</button><button data-action="queue" data-id="${t.id}" aria-label="Queue ${esc(t.title)}">+ QUEUE</button><button data-action="addtoset" data-id="${t.id}" aria-label="Add ${esc(t.title)} to a set">+ SET</button><button class="iconbtn ${state.liked.includes(t.id)?'liked':''}" data-action="like" data-id="${t.id}" aria-label="${state.liked.includes(t.id)?'Unlike':'Like'} ${esc(t.title)}">${state.liked.includes(t.id)?'♥':'♡'}</button></div></article>`).join('');
const results=tracks.filter(t=>[t.title,t.artist,t.album,t.mood,String(t.bpm)].join(' ').toLowerCase().includes(searchText.toLowerCase()));$('#resultCount').textContent=`${results.length} CUT${results.length===1?'':'S'}`;$('#searchResults').innerHTML=results.length?results.map(row).join(''):'<p class="empty">Nothing on that frequency. Try a title, artist or tempo.</p>';
const artistResults=searchText.trim()?artistDirectory.filter(a=>[a.name,a.genre,a.type,a.location,a.bio,a.album,a.year,a.coverBrief,a.subgenre].join(' ').toLowerCase().includes(searchText.toLowerCase())):[];$('#artistResultCount').textContent=searchText.trim()?`${artistResults.length} MATCH${artistResults.length===1?'':'ES'}`:'TYPE TO SEARCH';$('#artistSearchResults').innerHTML=artistResults.length?artistResults.slice(0,12).map(a=>`<article class="item artist-result"><img src="${esc(a.image)}" alt=""><div><h3><a href="#artist/${esc(a.id)}">${esc(a.name)} ↗</a></h3><p>${esc(a.album)} · ${esc(a.genre)} · ${esc(a.year)}</p></div><a class="result-link" href="#artist/${esc(a.id)}">VIEW ARTIST</a></article>`).join(''):searchText.trim()?'<p class="empty">No matching artists or releases.</p>':'<p class="empty">Artist and release matches will appear here as you type.</p>';
$('#libraryList').innerHTML=state.liked.map(byId).filter(Boolean).map(row).join('')||'<p class="empty">Your shelf is clear. Save a track to bring it here.</p>';
$('#queueList').innerHTML=state.queue.map((id,i)=>{const t=byId(id);return `<article class="item ${i===state.current?'playing':''}" data-track-id="${t.id}"><img src="${t.cover}" alt=""><div><h3>${String(i+1).padStart(2,'0')} / ${esc(t.title)}</h3><p>${esc(t.artist)} · ${t.duration}</p></div><div class="item-actions"><button data-action="playq" data-index="${i}">PLAY</button><button data-action="addtoset" data-id="${t.id}">+ SET</button><button data-action="removeq" data-index="${i}" ${state.queue.length===1?'disabled':''} aria-label="Remove ${esc(t.title)} from queue">REMOVE</button></div></article>`}).join('');$('#queueBadge').textContent=`${state.queue.length} IN THE RUNNING ORDER`;
const chosen=$('#playlistTrack').value;$('#playlistTrack').innerHTML=tracks.map(t=>`<option value="${t.id}">${esc(t.title)} — ${esc(t.artist)}</option>`).join('');if(chosen)$('#playlistTrack').value=chosen;
const playlistNames=Object.keys(state.playlists);const selectedSet=$('#playlistSelect').value;$('#playlistSelect').innerHTML=playlistNames.map(name=>`<option value="${esc(name)}">${esc(name)}</option>`).join('')||'<option value="">Create a set first</option>';if(selectedSet&&state.playlists[selectedSet])$('#playlistSelect').value=selectedSet;$('#dialogPlaylistSelect').innerHTML=$('#playlistSelect').innerHTML;
$('#playlistArea').innerHTML=Object.entries(state.playlists).map(([name,ids])=>`<section class="playlist"><div class="playlist-head"><h3>${esc(name)} <small>${ids.length} CUTS</small></h3><div><button data-action="playset" data-name="${esc(name)}">REPLACE QUEUE & PLAY</button><button data-action="queueset" data-name="${esc(name)}">ADD TO UP NEXT</button><button data-action="renameset" data-name="${esc(name)}">RENAME</button><button data-action="deleteset" data-name="${esc(name)}" aria-label="Delete ${esc(name)}">DELETE</button></div></div><div class="list">${ids.length?ids.map(byId).filter(Boolean).map((t,i)=>`<article class="item" data-track-id="${t.id}"><img src="${t.cover}" alt=""><div><h3>${esc(t.title)}</h3><p>${esc(t.artist)}</p></div><div class="item-actions"><button data-action="play" data-id="${t.id}">PLAY</button><button data-action="moveset" data-name="${esc(name)}" data-index="${i}" data-direction="-1" ${i===0?'disabled':''} aria-label="Move ${esc(t.title)} up">↑</button><button data-action="moveset" data-name="${esc(name)}" data-index="${i}" data-direction="1" ${i===ids.length-1?'disabled':''} aria-label="Move ${esc(t.title)} down">↓</button><button data-action="removefromset" data-name="${esc(name)}" data-index="${i}">REMOVE</button></div></article>`).join(''):'<p class="empty">Add a track above to start this set.</p>'}</div></section>`).join('');
updatePlayer();}
function route(){const target=(location.hash||'#home').slice(1);const communityRoute=/^(artists|artist\/[^/]+|signup|signin|profile|artist-apply|guidelines|privacy)$/.test(target);const view=communityRoute?'community':['home','search','library','queue','about'].includes(target)?target:'home';$$('[data-panel]').forEach(p=>p.classList.toggle('active',p.dataset.panel===view));$$('[data-view]').forEach(a=>a.classList.toggle('active',a.dataset.view===view||view==='community'&&a.dataset.view===(target==='artists'||target.startsWith('artist/')?'artists':'profile')));if(view==='search'&&target==='search')setTimeout(()=>$('#searchInput').focus(),50);window.scrollTo({top:0,behavior:'instant'});}
function theme(t){state.theme=t;document.documentElement.dataset.theme=t;$('#themeToggle').textContent=t==='dark'?'SWITCH TO LIGHT':'SWITCH TO DARK';document.querySelector('meta[name="theme-color"]').content=t==='dark'?'#11130f':'#f1eee2';save()}
document.addEventListener('click',e=>{const btn=e.target.closest('[data-action]');if(!btn)return;const {action,id,name}=btn.dataset;switch(action){case 'play':playTrack(id);break;case 'queue':addQueue(id);announce('Added to Up Next.');break;case 'like':toggleLike(id);break;case 'addtoset':{pendingSetTrack=id;if(!Object.keys(state.playlists).length){location.hash='library';$('#playlistName').focus();announce('Create a set first.');break}$('#dialogPlaylistSelect').innerHTML=Object.keys(state.playlists).map(n=>`<option value="${esc(n)}">${esc(n)}</option>`).join('');$('#addToSetDialog').showModal();break}case 'playq':playIndex(+btn.dataset.index);break;case 'removeq':{const i=+btn.dataset.index;if(state.queue.length===1)break;const wasCurrent=i===state.current;state.queue.splice(i,1);if(i<state.current)state.current--;else if(state.current>=state.queue.length)state.current=0;if(wasCurrent)loadTrack(!active.paused);else {render();prepareStandby();save()}break}case 'playset':{const ids=(state.playlists[name]||[]).filter(byId);if(ids.length){state.queue=[...ids];state.current=0;loadTrack(true)}break}case 'queueset':{const ids=(state.playlists[name]||[]).filter(byId);state.queue.push(...ids);render();prepareStandby();save();announce(`${ids.length} track${ids.length===1?'':'s'} added to Up Next.`);break}case 'renameset':{const next=prompt('New set name',name)?.trim();if(!next||next===name)break;if(state.playlists[next]){announce('A set with that name already exists.');break}state.playlists[next]=state.playlists[name];delete state.playlists[name];render();save();break}case 'deleteset':if(confirm(`Delete the set “${name}”?`)){delete state.playlists[name];render();save()}break;case 'moveset':{const list=state.playlists[name],i=+btn.dataset.index,j=i+(+btn.dataset.direction);if(!list||j<0||j>=list.length)break;[list[i],list[j]]=[list[j],list[i]];render();save();break}case 'removefromset':state.playlists[name]?.splice(+btn.dataset.index,1);render();save();break;}});
$('#playBtn').onclick=()=>active.paused?active.play().catch(()=>{}):active.pause();$('#nextBtn').onclick=()=>next();$('#prevBtn').onclick=previous;$('#playFeatured').onclick=()=>{state.queue=tracks.map(t=>t.id);state.current=0;loadTrack(true)};$('#shuffleFeatured').onclick=()=>{state.queue=tracks.map(t=>t.id);state.shuffle=true;state.current=Math.floor(Math.random()*state.queue.length);loadTrack(true)};
$('#shuffleBtn').onclick=()=>{state.shuffle=!state.shuffle;render();prepareStandby();save()};$('#repeatBtn').onclick=()=>{state.repeat=state.repeat==='off'?'all':state.repeat==='all'?'one':'off';render();prepareStandby();save()};$('#clearQueue').onclick=()=>{state.queue=[current().id];state.current=0;render();prepareStandby();save()};$('#clearState').onclick=()=>{if(confirm('Reset only your music likes, sets, queue and player preferences?')){localStorage.removeItem(storeKey);location.reload()}};$('#clearAllState').onclick=()=>{if(confirm('Reset all local Fuse Music data, including the music collection and community preview?')){localStorage.removeItem(storeKey);localStorage.removeItem('fuse-community-preview-v1');location.reload()}};
$('#themeToggle').onclick=()=>theme(state.theme==='dark'?'light':'dark');$('#volume').oninput=e=>{state.volume=+e.target.value;if(state.volume>0)lastAudibleVolume=state.volume;active.volume=state.volume;$('#muteBtn').textContent=state.volume===0?'MUTED':'VOL';updatePlayer();save()};$('#muteBtn').onclick=()=>{if(state.volume>0){lastAudibleVolume=state.volume;state.volume=0}else state.volume=lastAudibleVolume||.78;$('#volume').value=state.volume;active.volume=state.volume;updatePlayer();save()};$('#seek').oninput=e=>{if(Number.isFinite(active.duration))active.currentTime=(+e.target.value/1000)*active.duration;updateSeekA11y()};$('#searchInput').oninput=e=>{searchText=e.target.value;render();if(location.hash!=='#search')location.hash='search'};
$('#newPlaylist').onclick=()=>{const name=$('#playlistName').value.trim();if(!name){$('#playlistName').focus();return}if(state.playlists[name]){announce('A set with that name already exists.');return}state.playlists[name]=[];$('#playlistName').value='';render();$('#playlistSelect').value=name;save()};$('#addToPlaylist').onclick=()=>{const name=$('#playlistSelect').value;if(!name){$('#playlistName').focus();announce('Create a set first.');return}const id=$('#playlistTrack').value;if(!state.playlists[name].includes(id))state.playlists[name].push(id);else announce('That track is already in this set.');render();save()};$('#confirmAddToSet').onclick=e=>{e.preventDefault();const name=$('#dialogPlaylistSelect').value;if(name&&pendingSetTrack&&!state.playlists[name].includes(pendingSetTrack)){state.playlists[name].push(pendingSetTrack);save();render();announce(`Added to ${name}.`)}$('#addToSetDialog').close();pendingSetTrack=''};$('#shortcutHelp').onclick=()=>$('#shortcuts').showModal();
$('#playLiked').onclick=()=>{const ids=state.liked.filter(byId);if(!ids.length){announce('Save a track first.');return}state.queue=[...ids];state.current=0;loadTrack(true)};$('#shuffleLiked').onclick=()=>{const ids=state.liked.filter(byId).sort(()=>Math.random()-.5);if(!ids.length){announce('Save a track first.');return}state.queue=ids;state.current=0;loadTrack(true)};
$('#exportCollection').onclick=()=>{const community=localStorage.getItem('fuse-community-preview-v1');const payload={format:'fuse-music-backup',version:1,exportedAt:new Date().toISOString(),music:state,community:community?JSON.parse(community):null};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`fuse-music-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),0)};
$('#importCollection').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const payload=JSON.parse(await file.text());if(payload.format!=='fuse-music-backup'||payload.version!==1||!payload.music||typeof payload.music!=='object')throw Error();if(!confirm('Replace the local Fuse Music collection and community preview with this backup?'))return;localStorage.setItem(storeKey,JSON.stringify(payload.music));if(payload.community)localStorage.setItem('fuse-community-preview-v1',JSON.stringify(payload.community));location.reload()}catch{announce('That file is not a valid Fuse Music backup.')}finally{e.target.value=''}};
for(const el of [audioA,audioB]){el.addEventListener('timeupdate',()=>{if(el!==active)return;$('#elapsed').textContent=fmt(el.currentTime);if(Number.isFinite(el.duration)){$('#seek').value=Math.floor(el.currentTime/el.duration*1000);updateSeekA11y();if(state.repeat==='one'&&el.duration-el.currentTime<.12){el.currentTime=0;el.play().catch(()=>{})}else if(el.duration-el.currentTime<.52)transition()}});el.addEventListener('loadedmetadata',()=>{if(el===active){$('#duration').textContent=fmt(el.duration);updateSeekA11y()}});el.addEventListener('play',()=>{if(el===active)updatePlayer()});el.addEventListener('pause',()=>{if(el===active)updatePlayer()});el.addEventListener('ended',()=>{if(el===active&&!fading)next(true)});}
document.addEventListener('pointerdown',()=>{if(standbyPrimed||!standby.src)return;standbyPrimed=true;standby.muted=true;standby.play().then(()=>{standby.pause();standby.currentTime=0;standby.muted=false}).catch(()=>{crossfadeAllowed=false;standby.muted=false})},{once:true});
if('mediaSession' in navigator){const handlers={play:()=>active.play(),pause:()=>active.pause(),previoustrack:previous,nexttrack:()=>next(),seekto:d=>{if(Number.isFinite(d.seekTime))active.currentTime=Math.min(active.duration||d.seekTime,Math.max(0,d.seekTime))},seekbackward:d=>{active.currentTime=Math.max(0,active.currentTime-(d.seekOffset||10))},seekforward:d=>{active.currentTime=Math.min(active.duration||Infinity,active.currentTime+(d.seekOffset||10))}};for(const [action,handler] of Object.entries(handlers)){try{navigator.mediaSession.setActionHandler(action,handler)}catch{}}}
window.addEventListener('hashchange',route);document.addEventListener('keydown',e=>{if(e.altKey||e.ctrlKey||e.metaKey||['INPUT','SELECT','TEXTAREA','BUTTON','A'].includes(document.activeElement.tagName)||$('#shortcuts').open)return;const key=e.key.toLowerCase();if(e.code==='Space'){e.preventDefault();$('#playBtn').click()}else if(e.key==='ArrowRight'){e.preventDefault();next()}else if(e.key==='ArrowLeft'){e.preventDefault();previous()}else if(key==='s')$('#shuffleBtn').click();else if(key==='r')$('#repeatBtn').click();else if(key==='/'){e.preventDefault();location.hash='search';$('#searchInput').focus()}else if(key==='?')$('#shortcuts').showModal()});
fetch('artists.json').then(r=>r.ok?r.json():[]).then(list=>{artistDirectory=Array.isArray(list)?list:[];render()}).catch(()=>{});
theme(state.theme==='light'?'light':'dark');$('#volume').value=state.volume;active.src=current().src;active.volume=state.volume;render();prepareStandby();route();
